import type { Game } from "./types";

export const games: Game[] = [
  {
    slug: "money-heist",
    name: "Money Heist",
    shortName: "Money Heist",
    tagline: "Unlock the safe. Claim the cash.",
    description:
      "A free-to-play code game where every player holds a unique code. When the heist goes live, only the winning code cracks the safe — and takes home up to £10,000.",
    status: "live",
    theme: {
      primary: "#C80015",
      accent: "#FFE200",
      gradient: "from-[#410001] via-[#1a0001] to-[#070708]",
      cardGlow: "rgba(200,0,21,0.3)",
    },
    figmaEmbedSrc:
      "https://embed.figma.com/proto/9EIgAKApJ6kznmNZ84HJ83/Money-Heist?page-id=389%3A675&node-id=389-816&viewport=323%2C288%2C0.14&scaling=scale-down&content-scaling=fixed&starting-point-node-id=389%3A816&embed-host=share",
    heroImageAlt: "Money Heist — safe cracking game",
    badge: "FREE TO PLAY",
    globalStats: {
      activePlayers: "186K",
      totalPrizes: "€3.1M",
      markets: 6,
      roundsPlayed: "11.4M",
    },
    regions: [
      {
        code: "BR",
        name: "Brazil",
        flag: "🇧🇷",
        activePlayers: 62000,
        totalPrizesAwarded: "R$980K",
        engagementRate: 91,
        roundsPlayed: "3.8M",
        avgSessionMinutes: 5,
      },
      {
        code: "RO",
        name: "Romania",
        flag: "🇷🇴",
        activePlayers: 38500,
        totalPrizesAwarded: "€420K",
        engagementRate: 94,
        roundsPlayed: "2.4M",
        avgSessionMinutes: 4,
      },
      {
        code: "PL",
        name: "Poland",
        flag: "🇵🇱",
        activePlayers: 31200,
        totalPrizesAwarded: "€310K",
        engagementRate: 89,
        roundsPlayed: "1.9M",
        avgSessionMinutes: 4,
      },
      {
        code: "BE",
        name: "Belgium",
        flag: "🇧🇪",
        activePlayers: 24800,
        totalPrizesAwarded: "€290K",
        engagementRate: 92,
        roundsPlayed: "1.5M",
        avgSessionMinutes: 4,
      },
      {
        code: "RS",
        name: "Serbia",
        flag: "🇷🇸",
        activePlayers: 18400,
        totalPrizesAwarded: "€185K",
        engagementRate: 87,
        roundsPlayed: "1.1M",
        avgSessionMinutes: 3,
      },
      {
        code: "GR",
        name: "Greece",
        flag: "🇬🇷",
        activePlayers: 11100,
        totalPrizesAwarded: "€115K",
        engagementRate: 85,
        roundsPlayed: "710K",
        avgSessionMinutes: 3,
      },
    ],
    prizePool: {
      headline: "£10,000",
      subheadline: "plus 1,000+ more prizes",
      breakdown: [
        { label: "Jackpot Code", value: "£10,000", count: 1, highlight: true },
        { label: "Winning Codes each", value: "£500", count: 10 },
        { label: "Winning Codes worth", value: "£5 Free Bets", count: 1000 },
      ],
    },
    howToPlay: [
      {
        step: 1,
        title: "Secure Your Codes",
        description:
          "Enter for free and receive a unique code. Every player gets the same fair chance at cracking the safe.",
      },
      {
        step: 2,
        title: "The Heist Begins",
        description:
          "Once every code is sold, the countdown ends and the Money Heist goes live for all players simultaneously.",
      },
      {
        step: 3,
        title: "Crack the Safe",
        description:
          "When the heist runs, the safe opens for one winning code. If it's yours, you walk away with the jackpot — or one of 1,000+ other prizes.",
      },
    ],
  },
  {
    slug: "hunch-superstreak",
    name: "Hunch Superstreak",
    shortName: "Superstreak",
    tagline: "Predict. Streak. Win big.",
    description:
      "A daily prediction game where players answer football questions to build streaks. Higher streaks unlock bigger prizes — from free spins to cash payouts.",
    status: "live",
    theme: {
      primary: "#1B6B3A",
      accent: "#FFE200",
      gradient: "from-[#0d3320] via-[#0a1f14] to-[#070708]",
      cardGlow: "rgba(27,107,58,0.3)",
    },
    figmaEmbedSrc: null,
    heroImageAlt: "Hunch Superstreak — football prediction game",
    badge: "FREE TO PLAY",
    globalStats: {
      activePlayers: "312K",
      totalPrizes: "R$16.8M",
      markets: 6,
      roundsPlayed: "54M",
    },
    regions: [
      {
        code: "BR",
        name: "Brazil",
        flag: "🇧🇷",
        activePlayers: 248000,
        totalPrizesAwarded: "R$12.8M",
        engagementRate: 88,
        roundsPlayed: "42.1M",
        avgSessionMinutes: 6,
      },
      {
        code: "RO",
        name: "Romania",
        flag: "🇷🇴",
        activePlayers: 24500,
        totalPrizesAwarded: "€680K",
        engagementRate: 86,
        roundsPlayed: "4.3M",
        avgSessionMinutes: 5,
      },
      {
        code: "PL",
        name: "Poland",
        flag: "🇵🇱",
        activePlayers: 18200,
        totalPrizesAwarded: "€490K",
        engagementRate: 83,
        roundsPlayed: "3.1M",
        avgSessionMinutes: 5,
      },
      {
        code: "BE",
        name: "Belgium",
        flag: "🇧🇪",
        activePlayers: 11400,
        totalPrizesAwarded: "€310K",
        engagementRate: 81,
        roundsPlayed: "2.0M",
        avgSessionMinutes: 4,
      },
      {
        code: "RS",
        name: "Serbia",
        flag: "🇷🇸",
        activePlayers: 6800,
        totalPrizesAwarded: "€145K",
        engagementRate: 79,
        roundsPlayed: "1.4M",
        avgSessionMinutes: 4,
      },
      {
        code: "GR",
        name: "Greece",
        flag: "🇬🇷",
        activePlayers: 3100,
        totalPrizesAwarded: "€72K",
        engagementRate: 77,
        roundsPlayed: "1.1M",
        avgSessionMinutes: 4,
      },
    ],
    prizePool: {
      headline: "R$50,000",
      subheadline: "Ouro tier monthly jackpot",
      breakdown: [
        {
          label: "Ouro (Gold) — Top leaderboard",
          value: "R$50,000",
          count: 16,
          highlight: true,
        },
        {
          label: "Prata (Silver) — Mid leaderboard",
          value: "R$70,000 pool",
          count: 500,
        },
        {
          label: "Bronze — Free Spins",
          value: "Giros Grátis",
          count: 2000,
        },
      ],
    },
    howToPlay: [
      {
        step: 1,
        title: "Answer Daily Questions",
        description:
          "Each day features a set of football questions. Answer correctly to build your streak and climb the leaderboard.",
      },
      {
        step: 2,
        title: "Build Your Streak",
        description:
          "Consecutive correct answers grow your streak level. The higher the streak, the bigger the potential prize you can unlock.",
      },
      {
        step: 3,
        title: "Climb the Leaderboard",
        description:
          "Points accumulate across the bi-weekly period. Top finishers in Gold, Silver, and Bronze tiers all take home prizes.",
      },
    ],
  },
  {
    slug: "super-streak",
    name: "SuperStreak",
    shortName: "SuperStreak",
    tagline: "Streak your way to the top.",
    description:
      "A next-generation streak challenge game where players build consecutive winning runs across sports events. The longer the streak, the bigger the multiplier — and the prize.",
    status: "coming-soon",
    launchDate: "Q3 2026",
    theme: {
      primary: "#6B21A8",
      accent: "#FFE200",
      gradient: "from-[#2d0a52] via-[#1a0630] to-[#070708]",
      cardGlow: "rgba(107,33,168,0.3)",
    },
    figmaEmbedSrc: null,
    heroImageAlt: "SuperStreak — streak challenge game",
    badge: "COMING SOON",
    globalStats: {
      activePlayers: "—",
      totalPrizes: "—",
      markets: 6,
      roundsPlayed: "—",
    },
    regions: [
      {
        code: "BR",
        name: "Brazil",
        flag: "🇧🇷",
        activePlayers: 0,
        totalPrizesAwarded: "—",
        engagementRate: 0,
        roundsPlayed: "—",
        avgSessionMinutes: 0,
      },
      {
        code: "RO",
        name: "Romania",
        flag: "🇷🇴",
        activePlayers: 0,
        totalPrizesAwarded: "—",
        engagementRate: 0,
        roundsPlayed: "—",
        avgSessionMinutes: 0,
      },
      {
        code: "PL",
        name: "Poland",
        flag: "🇵🇱",
        activePlayers: 0,
        totalPrizesAwarded: "—",
        engagementRate: 0,
        roundsPlayed: "—",
        avgSessionMinutes: 0,
      },
      {
        code: "BE",
        name: "Belgium",
        flag: "🇧🇪",
        activePlayers: 0,
        totalPrizesAwarded: "—",
        engagementRate: 0,
        roundsPlayed: "—",
        avgSessionMinutes: 0,
      },
      {
        code: "RS",
        name: "Serbia",
        flag: "🇷🇸",
        activePlayers: 0,
        totalPrizesAwarded: "—",
        engagementRate: 0,
        roundsPlayed: "—",
        avgSessionMinutes: 0,
      },
      {
        code: "GR",
        name: "Greece",
        flag: "🇬🇷",
        activePlayers: 0,
        totalPrizesAwarded: "—",
        engagementRate: 0,
        roundsPlayed: "—",
        avgSessionMinutes: 0,
      },
    ],
    prizePool: {
      headline: "TBA",
      subheadline: "Prize structure to be confirmed",
      breakdown: [
        { label: "Streak Jackpot", value: "TBA", count: 1, highlight: true },
        { label: "Streak Multiplier Prizes", value: "TBA", count: 50 },
        { label: "Free Bet Rewards", value: "TBA", count: 500 },
      ],
    },
    howToPlay: [
      {
        step: 1,
        title: "Pick Your Events",
        description:
          "Select sports events each day to build the foundation of your streak. Every correct pick extends your run.",
      },
      {
        step: 2,
        title: "Build the Streak",
        description:
          "Each consecutive win multiplies your potential prize. The further you push, the higher the reward — but one wrong pick resets the streak.",
      },
      {
        step: 3,
        title: "Cash Out or Push On",
        description:
          "At key milestones, choose to bank your prize or risk it to go higher. The biggest jackpots go to players who dare to keep streaking.",
      },
    ],
  },
];

export function getGame(slug: string): Game | undefined {
  return games.find((g) => g.slug === slug);
}
